// <auto-generated />
using System;
using BackInovationMap.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackInovationMap.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250722175741_AddEnlaceToConvocatoria")]
    partial class AddEnlaceToConvocatoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackInovationMap.Models.Articulador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccesoBeneficiarios")
                        .HasColumnType("text");

                    b.Property<string>("ActividadesFormulacionImplementacion")
                        .HasColumnType("text");

                    b.Property<bool?>("AdaptaDiferenciasTerritorios")
                        .HasColumnType("boolean");

                    b.Property<int?>("Anio")
                        .HasColumnType("integer");

                    b.Property<int?>("AntiguedadOferta")
                        .HasColumnType("integer");

                    b.Property<bool>("ApoyoFinanciero")
                        .HasColumnType("boolean");

                    b.Property<bool>("AsistenciaTecnica")
                        .HasColumnType("boolean");

                    b.Property<string>("BarrerasFuncionamientoInstrumento")
                        .HasColumnType("text");

                    b.Property<bool>("BonosBouchers")
                        .HasColumnType("boolean");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cobertura")
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("CompraPublica")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ConsideraCoordinacionOtrasEntidades")
                        .HasColumnType("boolean");

                    b.Property<string>("Contacto")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriteriosFocalizacionBeneficiarios")
                        .HasColumnType("text");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DepartamentosMunicipios")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool?>("DescritoDocumentoInterno")
                        .HasColumnType("boolean");

                    b.Property<bool?>("DisenadoPorLeyOJuez")
                        .HasColumnType("boolean");

                    b.Property<bool?>("DisenadoPorPolitica")
                        .HasColumnType("boolean");

                    b.Property<bool?>("DisponibilidadRecursos")
                        .HasColumnType("boolean");

                    b.Property<string>("Entidad")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Eventos")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ExistenAlternativasInstrumento")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FormacionTalentoHumano")
                        .HasColumnType("boolean");

                    b.Property<string>("GestionAprendizajesInstrumento")
                        .HasColumnType("text");

                    b.Property<string>("GestionInformacionInstrumento")
                        .HasColumnType("text");

                    b.Property<string>("GestionOrganizativa")
                        .HasColumnType("text");

                    b.Property<bool>("IncentivosTributarios")
                        .HasColumnType("boolean");

                    b.Property<string>("InstrumentosOfertados")
                        .HasColumnType("text");

                    b.Property<bool>("InstrumentosRegulatorios")
                        .HasColumnType("boolean");

                    b.Property<string>("InsumosFormulacionImplementacion")
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("numeric");

                    b.Property<string>("MonitoreoEvaluacionInstrumento")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ObjetivoCalidad")
                        .HasColumnType("text");

                    b.Property<string>("ObjetivoClusterEncadenamientos")
                        .HasColumnType("text");

                    b.Property<string>("ObjetivoComercializacion")
                        .HasColumnType("text");

                    b.Property<string>("ObjetivoComercioElectronico")
                        .HasColumnType("text");

                    b.Property<string>("ObjetivoCrecimientoSostenible")
                        .HasColumnType("text");

                    b.Property<string>("ObjetivoEmprendimiento")
                        .HasColumnType("text");

                    b.Property<string>("ObjetivoFinanciacion")
                        .HasColumnType("text");

                    b.Property<string>("ObjetivoFormacionCapitalHumano")
                        .HasColumnType("text");

                    b.Property<string>("ObjetivoFormalizacion")
                        .HasColumnType("text");

                    b.Property<string>("ObjetivoInclusionFinanciera")
                        .HasColumnType("text");

                    b.Property<string>("ObjetivoInnovacion")
                        .HasColumnType("text");

                    b.Property<string>("ObjetivoInvestigacion")
                        .HasColumnType("text");

                    b.Property<string>("ObjetivoTransferenciaConocimientoTecnologia")
                        .HasColumnType("text");

                    b.Property<string>("ObjetivosFormulacionInstrumento")
                        .HasColumnType("text");

                    b.Property<string>("OrigenInstrumento")
                        .HasColumnType("text");

                    b.Property<string>("Pagina")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PersonalApoyoFormulacionImplementacion")
                        .HasColumnType("text");

                    b.Property<string>("PoblacionObjetivo")
                        .HasColumnType("text");

                    b.Property<decimal?>("PorcentajeCalidad")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PorcentajeClusterEncadenamientos")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PorcentajeComercializacion")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PorcentajeComercioElectronico")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PorcentajeCrecimientoSostenible")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PorcentajeEmprendimiento")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PorcentajeFinanciacion")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PorcentajeFormacionCapitalHumano")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PorcentajeFormalizacion")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PorcentajeInclusionFinanciera")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PorcentajeInnovacion")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PorcentajeInvestigacion")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PorcentajeTransferenciaConocimientoTecnologia")
                        .HasColumnType("numeric");

                    b.Property<bool>("PremiosReconocimientos")
                        .HasColumnType("boolean");

                    b.Property<string>("ProductosGeneradosInstrumento")
                        .HasColumnType("text");

                    b.Property<decimal?>("RecursosCooperacion")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RecursosEsfuerzoFiscal")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RecursosOtros")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RecursosPGN")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RecursosParafiscales")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RecursosPrivado")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RecursosSGR")
                        .HasColumnType("numeric");

                    b.Property<bool>("RedesColaboracion")
                        .HasColumnType("boolean");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RelacionConOtrosInstrumentos")
                        .HasColumnType("text");

                    b.Property<string>("ResultadosImpactosEsperados")
                        .HasColumnType("text");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SeleccionBeneficiarios")
                        .HasColumnType("text");

                    b.Property<bool>("SistemasInformacion")
                        .HasColumnType("boolean");

                    b.Property<bool?>("SolucionaFallaMercadoGobiernoArticulacion")
                        .HasColumnType("boolean");

                    b.Property<bool?>("TieneMarcoLogico")
                        .HasColumnType("boolean");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("TrazabilidadBeneficiarios")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsuariosAcademia")
                        .HasColumnType("text");

                    b.Property<string>("UsuariosEmprendedores")
                        .HasColumnType("text");

                    b.Property<string>("UsuariosEntidadesGobierno")
                        .HasColumnType("text");

                    b.Property<string>("UsuariosGrandesEmpresas")
                        .HasColumnType("text");

                    b.Property<string>("UsuariosMiPymes")
                        .HasColumnType("text");

                    b.Property<string>("UsuariosOrganizacionesSoporte")
                        .HasColumnType("text");

                    b.Property<string>("UsuariosPersonasNaturales")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Ciudad");

                    b.HasIndex("Departamento");

                    b.HasIndex("Tipo");

                    b.ToTable("Articuladores");
                });

            modelBuilder.Entity("BackInovationMap.Models.ArticuladorCompany", b =>
                {
                    b.Property<int>("ArticuladorId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TipoColaboracion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ArticuladorId", "CompanyId");

                    b.HasIndex("Activa");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TipoColaboracion");

                    b.ToTable("ArticuladorCompanies");
                });

            modelBuilder.Entity("BackInovationMap.Models.ArticuladorConvocatoria", b =>
                {
                    b.Property<int>("ArticuladorId")
                        .HasColumnType("integer");

                    b.Property<int>("ConvocatoriaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Responsabilidades")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Rol")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ArticuladorId", "ConvocatoriaId");

                    b.HasIndex("Activo");

                    b.HasIndex("ConvocatoriaId");

                    b.HasIndex("Rol");

                    b.ToTable("ArticuladorConvocatorias");
                });

            modelBuilder.Entity("BackInovationMap.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<string>("Contacto")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("numeric");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoActor")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BackInovationMap.Models.Convocatoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Clasificacion")
                        .HasColumnType("text");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Enlace")
                        .HasColumnType("text");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EstadoManual")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LineaOportunidad")
                        .HasColumnType("text");

                    b.Property<string>("PalabrasClave")
                        .HasColumnType("text");

                    b.Property<decimal?>("Presupuesto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Requisitos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaFin");

                    b.HasIndex("FechaInicio");

                    b.ToTable("Convocatorias");
                });

            modelBuilder.Entity("BackInovationMap.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Organizacion")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Rol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BackInovationMap.Models.ArticuladorCompany", b =>
                {
                    b.HasOne("BackInovationMap.Models.Articulador", "Articulador")
                        .WithMany("ArticuladorCompanies")
                        .HasForeignKey("ArticuladorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackInovationMap.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulador");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BackInovationMap.Models.ArticuladorConvocatoria", b =>
                {
                    b.HasOne("BackInovationMap.Models.Articulador", "Articulador")
                        .WithMany("ArticuladorConvocatorias")
                        .HasForeignKey("ArticuladorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackInovationMap.Models.Convocatoria", "Convocatoria")
                        .WithMany()
                        .HasForeignKey("ConvocatoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulador");

                    b.Navigation("Convocatoria");
                });

            modelBuilder.Entity("BackInovationMap.Models.Convocatoria", b =>
                {
                    b.HasOne("BackInovationMap.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BackInovationMap.Models.Articulador", b =>
                {
                    b.Navigation("ArticuladorCompanies");

                    b.Navigation("ArticuladorConvocatorias");
                });
#pragma warning restore 612, 618
        }
    }
}
